# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Reality Media
tagline:          'Reality Media'
description:      'The digital complement to Reality Media (MIT Press 2021)'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
plugins:          [jekyll-paginate]
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


